const assert=require('node:assert/strict');
const {rate,metricValue,summarize}=require('../app/static/js/temporal-summary.js');
const p=(start,end,total,hours,count,duration)=>({start,end,vehicle_total:total,observed_road_hours:hours,observation_count:count,duration_minutes:duration});
const groups=[{day_type:'weekday',vehicle_total:600,observed_road_hours:12,observation_count:3,periods:[p('07:00','09:00',400,4,2,120),p('09:00','17:00',200,8,1,480)]},{day_type:'weekend',vehicle_total:300,observed_road_hours:10,observation_count:2,periods:[p('07:00','09:00',100,2,1,120),p('09:00','17:00',200,8,1,480)]}];
let s=summarize({groups});
assert.equal(s.weekday,50);assert.equal(s.weekend,30);assert.ok(Math.abs(s.difference-66.6666667)<1e-6);
assert.equal(s.busiest[0].start,'07:00');assert.equal(s.maximum,500/6);
assert.equal(metricValue(groups[0].periods[0],'observation'),200);
assert.equal(metricValue(groups[0].periods[0],'hour'),100);
assert.equal(metricValue(groups[0].periods[0],'total'),400);
groups[0].vehicle_total=0;s=summarize({groups});assert.equal(s.weekday,0);assert.equal(s.difference,-100);
groups[1].vehicle_total=0;assert.equal(summarize({groups}).difference,null);
groups[1].observation_count=0;assert.equal(summarize({groups}).weekend,null);
assert.equal(rate({vehicle_total:12,observation_count:1,observed_road_hours:0}),null);
assert.equal(metricValue({vehicle_total:0,observation_count:0},'total'),null);
assert.equal(metricValue({vehicle_total:0,observation_count:1},'total'),0);
assert.equal(summarize({groups:[]}).maximum,null);
s=summarize({groups:[{day_type:'weekday',periods:[p('07:00','09:00',20,2,1,120),p('09:00','17:00',80,8,1,480)]}]});
assert.equal(s.busiest.length,2);
console.log('Temporal summary: weighted hours, record denominator, signed difference, missing/zero, ties and empty data passed');
